### ISSUE TITLE
Encoding issue when accessing object.container.album.musicAlbum

### ISSUE THREAD

**Issue by tobe2bcon** [ChriD/node-raumserver#101]
Hi again,
I'm currently trying to read objects contained in 'object.container.person.musicArtist'. This container usually contains two kinds of further objects. The first is 'object.container.trackContainer.allTracks', from which I can get all tracks. The second kind of container exists per album and is called 'object.container.album.musicAlbum'. It includes all tracks of the respective album. In general the http request looks like this: http://<IP:port>/raumserver/data/getMediaList?id=0/My Music/Artists/Name of Artist+Name of Album

However it's not possible to send this request to node-raumserver without errors, since the names of the artist and the album may include spaces, symbols (e.g. / or &) or german vowels (ä, ö, ü).  Also the + between artist and name might cause a problem. I am aware that spaces have to be encoded by %2520. But what about the other symbols and letters?

Does anyone know, how to overcome this issue? Any hint is welcome. Thamk you very much.

Best
Thomas

**Comment by ChriD** [comment]
https://www.urlencoder.org/ is your friend
Data passed in urls always has to be encoded. That means that special chars like space and + aso are converted to % values
Give it a try

**Comment by tobe2bcon** [comment]
Thank you. This tool is really quite helpful. However it doesn't
resolve the problem.
I used this url to find tracks:
/raumserver/data/getMediaList?id=0/My%20Music/Albumsand found this one
(beside others of course): id:    "0/My
Music/Albums/+04_Partyhits%20deutsch"
/+04_Partyhits%20deutsch was encoded to /%2F%2B04_Partyhits%2520deutsch
I then put
/raumserver/data/getMediaList?id=0/My%20Music/Albums/%2F%2B04_Partyhits
%2520deutsch to  the url, which unfortunately resultet in "error: true"
again. So this is obviously not sufficient to read tracks included in
an album.
How do you do this?
BestThomas




Am Freitag, dem 26.11.2021 um 11:05 -0800 schrieb Christian:

**Comment by tobe2bcon** [comment]
OK got it. In the beginning I used the JS command  codedURL = encodeURI(uncodedURL). This command does not convert all symbols such as '+'.
The correct command instead is codedURL = encodeURIComponent(uncodedURL)

Hope this helps all users struggling with coding URLs
