### ISSUE TITLE
Generate Executables for Linux/Windows and Maybe Mac?

### ISSUE THREAD

**Issue by ChriD** [ChriD/node-raumserver#16]
Generate Executables for Linux/Windows and Maybe Mac?

**Comment by holli73** [comment]
hello,

i could offer some hw resources for build - like pi 2/3 - mac and x32/64 if needed. 

best regards
holli

**Comment by kaloschke** [comment]
Hi,

if I understand right, you can help me for installing node.raumfeld on a windows 10 pc?
The latest node.js installer is V6.10.3, but Chris wants a version later 7.x
What can I do?

Regards Kaloschke

**Comment by ChriD** [comment]
Choode the "Current" (Latest Features) node version
Go to   https://nodejs.org/en/ and Choose v7.10.0 current not the LTS version

**Comment by kaloschke** [comment]
Thank you very much. That works for me.

**Comment by ChriD** [comment]
I have decided to not create executables. Its too much work to maintain
