### ISSUE TITLE
Zonen-Befehle funktionieren nicht

### ISSUE THREAD

**Issue by mee0n** [ChriD/node-raumserver#17]
Hallo @ChriD ,

Wenn ich CreateZone (gleich bei AddToZone) verwende wie ich es mit deinem raumserver schon immer getan habe oder es mittels deines test-html versuche führt das immer zu folgendem Fehler.

Rückmeldung des test-html für CreateZone (das &_=1492180822922 kommt nicht von mir):
```
{
requestUrl :  "/raumserver/controller/createZone?id=Flur&_=1492180822922",
action :  "createZone",
error :  true,
msg :  "Action was rejected",
data : {
errorMessage :  "TypeError: Cannot read property 'getSettings' of undefined",
errorData :  null
}
}
```

Kannst du mir da weiterhelfen?

Vielen Dank schon mal im Voraus!
mee0n

**Comment by ChriD** [comment]
Hallo @mee0n 
Sorry, ist ein Bug im node-raumkernel der in der letzten Version reingekommen ist.
Habe den node raumkernel aktaulisiert! npm update sollte funktionieren.

**Comment by mee0n** [comment]
Danke! Ist ja super, dass du das so schnell beheben konntest!
Ich kenne mich mit dem npm-Dingens nicht aus, aber wenn der Prompt nach 3 Sekunden, ohne Output zu erzeugen, zurückkommt dann hat das mit dem npm update wohl nicht funktioniert, oder?

**Comment by ChriD** [comment]
Sehr gut :) passt
