### ISSUE TITLE
Playlist laden mit TuneIn-Track

### ISSUE THREAD

**Issue by mee0n** [ChriD/node-raumserver#18]
Hallo @ChriD ,

ein anderes Problem habe ich momentan noch mit dem Laden einer Playlist.
Habe eine Playlist deren erster und einziger Track ein TuneIn-Radiosender ist, da ich nicht wusste wie ich den Radiosender direkt laden kann. Unter dem alten raumserver hat das so einwandfrei funktioniert.
Nun aber nicht mehr. Die Befehle werden fehlerfrei abgesetzt, etc. aber er lädt sie einfach nicht. Schaue ich parallel in die App lädt er kurz was und zeigt dann "This music is not available" an und macht dann nichts weiter.
Mit einer Test-Playlist deren erster und einziger Track ein Tidal-Titel ist funktioniert es einwandfrei.

Hast du dazu eine Idee?
mee0n

**Comment by ChriD** [comment]
Welcher Radiosender ist es denn? Dann kann ich es probieren und das Problem eventuell nachvollziehen.

**Comment by mee0n** [comment]
Absolut relax
Damit man beim Aufwachen nicht gleich aus dem Bett fällt. ^^

Ein weiteres Phänomen (evtl. in einem eigenen Issue sinnvoll) ist, dass ich die Playlist (beim alten Raumserver zumindest; der Neue lief bei mir bisher noch nie fehlerfrei) immer zweimal hintereinander per LoadPlaylist laden musste. Wenn ich nur einmal geladen habe hat sie sich zu Tode geladen. Ist auch auf die Radio-Playlist bezogen.

**Comment by ChriD** [comment]
@mee0n 

**TuneIn laden**
hmm.. Funktioniert bei mir einwandfrei. Habe eine Payliste "radiotest" erstellt mit "Absolut relax" als radio.
Die Playlist bzw. das Radio wird wird sauber  geladen und das Radio gespielt

**Playlisten laden**
Auch das Playlisten laden geht bei mir. Ich muss nicht 2 mal laden.
Ich habs jetzt über 20ig mal verscht. Und jedes mal hat es geklappt (habs mit Playlisten mit ein paar einträgen und mit palylisten über 100 Einträge probiert)
Was natürlich nicht funktioniert ist wenn ich eine Playliste laden will die es nicht gibt. Dann kreiselt das ding ins unendliche.

Wie sieht den dein setup aus?

**Comment by mee0n** [comment]
@ChriD 
**Playlisten laden**
Wie gesagt, das konnte ich bisher nur beim alten Raumserver feststellen, den Neuen richte ich ja quasi jetzt erst ein. Kann also sein das das doppelt Laden nun einwandfrei funktioniert > Scheint sogar gerade so der Fall zu sein. :)

**TuneIn**
Bei mir geht das über die App einwandfrei; über den raumserver leider nicht. Habe es eben nochmal getestet. 
Ich glaube ich habe den Sündenbock ...
Meine Playlist heißt **BuT_WakeUp**. Ich konnte in der Debug-Ausgabe sehen das er den Unterstrich zu %5f oder sowas umgesetzt wird; eben html-codiert denke ich. Wenn ich den Radiosender in eine Playlist **test** packe und lade, dann geht es; habe auch meine BuT_WakeUp-Playliste neu erstellt; aber Fehler bleibt persistent.

**Comment by ChriD** [comment]
> Meine Playlist heißt BuT_WakeUp. Ich konnte in der Debug-Ausgabe sehen das er den Unterstrich zu %5f oder sowas umgesetzt wird; 
Okay. Ich sehe mir das mit dem _ an. Leerzeichen würde auf jeden Fall funktionieren ;-)

**Comment by mee0n** [comment]
Okay, danke dafür! Für mich passt das so erstmal. Ich komme auch ohne Unterstrich im Namen aus. ;)
mee0n

**Comment by ChriD** [comment]
Man kann nun auch Playlisten die `_` enthalten laden
