### ISSUE TITLE
FadeToVolume bei Zone ungleichmäßig

### ISSUE THREAD

**Issue by mee0n** [ChriD/node-raumserver#19]
Hallo @ChriD ,

wenn ich via
`/raumserver/controller/setVolume?value=1&id=Schlafzimmer&scope=zone`
einer ganzen Zone die gleiche Lautstärke verpasse, danach via
`/raumserver/controller/play?id=Schlafzimmer`
die Wiedergabe starte und danach via
`/raumserver/controller/fadeToVolume?value=25&id=Schlafzimmer&scope=zone&duration=60000`
die Lautstärke hochfahren möchte ist es oft so, dass nicht alle Lautsprecher in der Zone die gleiche Lautstärke haben. Wenn ich parallel mit der App zusehe, bleiben Laustprecher "hängen" und steigen erst verzögert sodass am Ende aber nicht der gleiche Lautstärkenwert erreicht wird. 

Lässt sich das beheben?
Ich schätze mal du lässt die Lautstärke gerade pro Lautsprecher relativ ansteigen; die Frage ist nur warum es manchmal zu Hängern und Verzögerungen kommt ... falls Diese nicht wegzubekommen sind (da Raumfeld-bedingt o.Ä.) müsste man evtl. dafür sorgen das sie trotzdem weiter ansteigen (auch wenn die eingestellte duration dabei quasi überschritten wird; aber ja eben theoretisch nicht für den verzögerten Lautsprecher) sodass am Ende alle Lautsprecher den eingestellten Wert erreicht haben.

Danke für deine Mühen!
mee0n

**Comment by ChriD** [comment]
Ich seh mir das mal genauer an. Aber jetzt kann ich schon mal sagen dass, das setzen der Lautstärke einer Zone nicht alle Räume auf die gleiche Lautstärk setzt. Das macht aber das Raumfeld System so.
Aber das andere was du beschreibst muss ich mir ansehen. Hab ich so noch nicht bemerkt

**Comment by mee0n** [comment]
Alles klar, danke. Dann bin ich mal in Wartestellung hierzu. Wäre ja perfekt wenn das für dich nachvollziehbar und perfektioniert wird. :)

**Comment by ChriD** [comment]
@mee0n 
Also. Bei mir funktioniert das  _ohne Hänger und Verzögerungen._   
FadeToVolume faded den Wert relativ bei allen Räumen. D.h also wenn du Raum A mit 40 und Raum B mit 20 hast und du fadest auf 60 wird Raum A 60 haben und Raum B 40. (weil der Request die Funktion von Raumfeld benutzt)

> wenn ich via
> /raumserver/controller/setVolume?value=1&id=Schlafzimmer&scope=zone
> einer ganzen Zone die gleiche Lautstärke verpasse

Das verpasst damir nicht den Räumen der ganzen Zone die selbe Lautstärke, sondern das verhält sich wie wenn du in der App den Volume-Drehknopf für die Zone bewegst.

Ich kann den Wunsch aber nachvollziehen und man kann ab der 0.0.7er version mit der option  `&equalRooms=1` den Wert der Räume über den `setVolume` request gleichsetzen.
Also dann in etwa so `setVolume?id=Kueche&scope=zone&value=30&equalRooms=1`

**Comment by mee0n** [comment]
@ChriD 
Ah, okay. Das mit den Verzögerungen muss ich mir beim neuen raumserver auch nochmal ansehen, entweder es ist weg oder ich kann dir eine noch genauere Fehlerbeschreibung liefern wenn es noch da ist.
Das mit der Option `&equalRooms` ist dann schon sehr cool, dass du die mit reingebaut hast. Danke dafür! :)
mee0n

**Comment by mee0n** [comment]
@ChriD 
Aaalso ... das lässt mir doch keine Ruhe und habe es deswegen gerade versucht nachzustellen.
So wie ich das verstehe setze ich mit ZoneVolume den Regler auf 1, wodurch dann aber relativ pro Box runtergestellt wird und das anscheinend ausgehend vom höchsten (Vermutung) Lautstärkewert. In der Debug-Ausgabe konnte ich deutlich sehen, das Boxen im Minus-Volume-Bereich landen ... das sind genau diese "Verzögerungen/Hänger". Wenn ich also zwei Boxen vorher auf 20 und 30 stehen habe, danach setVolumeZone auf 1 stelle ist die eine auf 1, die andere auf -9. daher sind am Schluss verschiedene Lautsärken angelegt. Somit müsstest du es bei dir auch nachstellen können. Das Problem ist hierbei also der Minusbereich.
mee0n

**Comment by ChriD** [comment]
Das mit den -Werten kann ich leider nicht ändern. Das ist by Design vom Raumfeld System. Das macht die Android App auch so. Ich finde es aber auch garnichtmal so schlecht.
Aber ich denke mit dem `equalRooms` ist dir sicherlich geholfen! Ein bisschen musst du noch warten auf die neue version, du könntest dir die libs aber schon vom github ziehen, da ist es schon drinnen

**Comment by mee0n** [comment]
@ChriD 
Alles klar, danke. Ich denke ich kann noch bis zum 0.0.7 warten. Weißt du denn schon wann du das releasen wirst?
Gibt es eigentlich eine Übersicht darüber welche Features du in Zukunft noch so planst evtl. sogar mit einer Roadmap (Versionsbezogen; nicht Zeit)

**Comment by ChriD** [comment]
So genau kann ich nicht sagen wann ich die version release. Dieses Wochende glaube ich nicht mehr. Aber so nächste WE oder früher.
BTW: Du kannst gerne Wünsche/Features für die Roadmap äußern.  (über die Issues)
