### ISSUE TITLE
getRederState missing friendly name of rooms

### ISSUE THREAD

**Issue by holli73** [ChriD/node-raumserver#20]
hello,

i try to use the node raumserver but i'm missing the friendly name of my rooms?

curl "http://obelix:18080/raumserver/data/getRendererState?listAll=true" |json -a data |json -a rooms

f.ex. returns:
```
[
  {
    "roomUDN": "uuid:50f23c84-0a1b-48de-ab44-10e9dd068f4e",
    "transportState": "STOPPED",
    "online": true,
    "volume": "46",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:b463e62d-b87a-4b4a-ab4d-bdee80821f78",
    "transportState": "STOPPED",
    "online": true,
    "volume": "33",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:8d10c182-e6e5-4c54-817e-9313877877f7",
    "transportState": "PLAYING",
    "online": true,
    "volume": "25",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:00287e64-0fcb-4e56-92da-30aaa0518b63",
    "transportState": "STOPPED",
    "online": true,
    "volume": "26",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:95ffde14-a056-452e-a4fb-4d9c068fdf4b",
    "volume": "52",
    "mute": "0",
    "online": true
  }
]
[
  {
    "roomUDN": "uuid:c7684d10-6548-4a4c-a9e7-6a31e178d8ac",
    "transportState": "STOPPED",
    "online": true,
    "volume": "26",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:02fe4938-45ce-4e13-b827-06a3fa45e3aa",
    "transportState": "STOPPED",
    "online": true,
    "volume": "42",
    "mute": "0"
  }
]
[
  {
    "roomUDN": "uuid:1a0c63af-481d-41e3-859b-b777616ee63e",
    "volume": "36",
    "mute": "0",
    "online": true
  }
]
```
with what request would i get the friendly name + roomUDN + state - f.ex. for a doorbell functionality - i need to ring on certain speaker depending on the states and after ring put them into the prev. state again - sure i can make my own matching for friendly name + roomUDN - but would be nice to have this in one request - and reading my code for friendly names is more readable as the udn's.

what do you think?

thanks
holli

**Comment by ChriD** [comment]
I've added the friendlyName and some more infos to the result of the renderer itself.
Additionally i have added the zoneConfiguration-RoomInformation to the result. I think this may fit your needs. Will be availabel on version 0.0.7

```

rooms : [
    {
        roomUDN :  "uuid:3f68f253-df2a-4474-8640-fd45dd9ebf88",
        transportState :  "PAUSED_PLAYBACK",
        online :  true,
        volume :  "51",
        mute :  "0",
        name :  "Küche",
        color :  "#0066ff",
        udn :  "uuid:3f68f253-df2a-4474-8640-fd45dd9ebf88",
        powerState :  "AUTOMATIC_STANDBY",
        renderer : [
            {
                udn :  "uuid:30e3c8cd-1ce0-4842-89d0-63ea58858cd8",
                name :  "Connector Küche"
            }
        ]
    }
],

```

**Comment by davidspr** [comment]
Hi, 
I am following this to implement the doorbell functionality as well, see https://github.com/ChriD/Raumserver/issues/20

Cool piece of software!
David

**Comment by holli73** [comment]
hello,

cool - happy easter - git pull - did do the trick.

thanks
holli
