### ISSUE TITLE
Nutzbarkeit der lokalen Buttons

### ISSUE THREAD

**Issue by mee0n** [ChriD/node-raumserver#21]
Hallo @ChriD ,

ist es möglich die lokalen Buttons (1-4) an einem Lautsprecher mit einem HTTP Befehl an den Raumserver zu belegen? Unter Umständen über einen "virtuellen Titel" wenn es nicht direkt geht.
Ich nutze so einen Workaround beispielsweise auch mit der Wecker-App "Alarmdroid". hier kann man sich auch per Internetradiosender wecken lassen. Nur statt dessen habe ich eine HTTP-Anfrage an den raumserver als URL eingetragen. und schon habe ich einen Raumfeld-Wecker. :D

Hintergrund ist eine kleine Schwäche der "OnlyApp"-Bedienung. Wenn Jemand an der Tür klingelt oder das Telefon läutet oder sonst was und man laut Musik hört, dann dauert es teils sehr lange (Handy entsperren > App öffnen > Warten bis Verbunden mit Host > Räume finden > Lautstärke öffnen > Mute) mit einem naheliegenden Smartphone, o.Ä. die Wohnung Stumm zu schalten. Wäre schön wenn ich in jedem Raum einfach auf Button 1 drücken könnte um einen "ToggleMuteAll" auszulösen.

Gruß
mee0n

**Comment by ChriD** [comment]
Das ist eine nette Idee. 
Ich werde das prüfen aber ich befürchte aber das wird nicht möglich sein. 
Einen "virtuellem Titel" kann man sicherlich hinterlegen. Die Buttons sind ja dazu da jegliche art von container zu speichern bzw. zu laden, aber damit einen request bzw. mute oder dgl. zu triggern wird wahrscheinlich nicht gehen.

**Comment by mee0n** [comment]
Kann denn der Container nicht auch vom Typ "loadUri" sein und die Uri ist dann ein HTTP request auf den eigenen raumserver?

**Comment by ChriD** [comment]
Nein das verstehst du glaub ich falsch.
Auf den Buttons sind  schon urls hinterlegt, aber das Raumfeldsystem setzt diese Url's direkt auf den MediaRenderer und führt diese nicht aus. D.h also wenn man dort eine request url vom raumserver hinterlegt würde das RF-System diese erstmal auf den renderer setzten und das bedeutet wiederrum das die gerade geladene url/playlist/album weg ist. Kann dan schon sein das der Renderer den request absetzt weil er ja die Daten lesen will, aber das bringt dann ja nichts mehr wenn die Titlelliste dann schon weg ist.

Das ist jetzt eine Vermutung, ich habe es noch nicht geprüft. Ich denke aber das es so sein wird.

**Comment by mee0n** [comment]
@ChriD 
Ah, okay. Alles klar. Ich habe auch noch eine andere Idee wie die Situation für mich gelöst werden könnte. Ich schreibe hierzu der Korrektheit halber einen neuen Issue.

**Comment by ChriD** [comment]
Reopen für kurze analyse

**Comment by ChriD** [comment]
Ich habe mir das angesehen und sehe derzeit keine möglichkeit das umzusetzen.
