### ISSUE TITLE
Zonen Lautstärkeregelung

### ISSUE THREAD

**Issue by mee0n** [ChriD/node-raumserver#24]
Hallo @ChriD ,

in Erweiterung zur Problemstellung in Issue #21 habe ich noch eine andere Idee die du mit dem raumserver umsetzen könntest. Wichtig ist mir ja quasi nur, recht schnell und am liebsten ohne App die Lautstärke über mehrere Räume hinweg runterdrehen bzw muten zu können.
Also folgende Idee:
Man sollte auf eine Zone eine Option setzen können die dann dafür sorgt, dass wenn man an einem Lautsprecher (egal welchem in der Zone) am Lautstärkeregler dreht, dieser quasi die Funktion des Lautstärkereglers einer Zone, analog des App-Reglers, übernimmt und somit auch alle anderen Lausprecher regelt. Somit könnte man die Lautstärke auch sehr schnell runter bringen bis zum mute was für meine Zwecke eine fast genauso gute Lösung darstellt wie der in Issue #21 beschriebenen Ansatz.
Hierbei ist der bekannte Minusbereich pro Lautsprecher tatsächlich nützlich damit nach dem wieder aufdrehen alle wieder die selbe Lautstärke haben wie vorher und nicht durch eine Limitierung bei 0 gleichgezogen wurden.

Würde sich das so umsetzen lassen?

Gruß
mee0n

**Comment by ChriD** [comment]
Hmm... Das wären sozusagen abhängige Presets wie ich sie mal für den alten Raumserver angedacht hatte
Aber du darfst nicht vergessen das der Lautstärkeregler die Laustärke vom renderer immer ändern wird, das kann ich nicht unterbinden. Man könnte dann schon die differenz der lautstärke auf die der anderern renderer in der zone übertragen, da müsste man halt hoffen das die dann so auch in den minusbereich gehen. (Über die Zonenänderung würde das nicht sauber laufen da der Lautstärkeregler ja wie oben erwähnt direkt die Lautstärke am renderer ändert)

Weiters ist ein Problem das man nicht erkennen kann wie die Lautstärke gesetzt wird. Das könnt dann natürlich zu Endlosschleifen führen. (Ich änder LS auf Speaker A, der Triggert die Änderung auf Speaker B, aber Speaker B muss ja auch auf die Volumeänderung reagieren und triggert dann wieder A...)

Da sind sehr viele Sachen zu bedenken und zu analysieren.
Ich muss auch ehrlich sagen dass das ganz unten auf der Prioliste steht!

**Comment by mee0n** [comment]
Okay, passt. Wenn eine Lösung gefunden werden kann, mit der etwas in der Art umsetzbar wäre, freue mich mich natürlich; eilig ist es eh' nicht. Dann wird bis dahin eben ein Workaround die Arbeit tun. :)

**Comment by ChriD** [comment]
Das ist leider nicht umsetzbar  :(

**Comment by mee0n** [comment]
Hm, schade. Danke, dass du dich damit noch auseinandergesetzt hast! :)
