### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by melksem** [ChriD/node-raumserver#25]
Hallo,

ich versuche gerade, das auf einem Pi3 mit openHABian zum Laufen zu bringen und scheitere grandios. Was mache ich falsch?

sudo apt-get install -y nodejs npm node

mkdir raumfeld
cd raumfeld/
npm install node-raumserver

[22:15:28] openhabian@openHABianPi:~/raumfeld$ node node_modules/node-raumserver/test.js
[22:15:30] openhabian@openHABianPi:~/raumfeld$ echo $?
1

[22:15:36] openhabian@openHABianPi:~/raumfeld$ npm start node-raumserver

> node-raumserver@0.0.6 start /home/openhabian/raumfeld/node_modules/node-raumserver
> node index.js

npm ERR! node-raumserver@0.0.6 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-raumserver@0.0.6 start script.
npm ERR! This is most likely a problem with the node-raumserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-raumserver
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start" "node-raumserver"
npm ERR! cwd /home/openhabian/raumfeld
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/openhabian/raumfeld/npm-debug.log
npm ERR! not ok code 0

Irgendwelche falschen/veralteten Versionen? Aber apt-get update/upgrade bringt nichts Neues... Ich bin ratlos.

Danke fürs helfen,
Marco

**Comment by ChriD** [comment]
Welche nodeJs version hast du installiert?

**Comment by melksem** [comment]
Hi,

ok, das hat erst mal funktioniert. Vielen Dank. Jetzt startet es damit:

`node node_modules/node-raumserver/test.js`

Kann ich erst mal weiter probieren, super :)

**Comment by melksem** [comment]
Funktioniert, juhu. Danke
