### ISSUE TITLE
add raumfeld devices manually

### ISSUE THREAD

**Issue by smindorf** [ChriD/node-raumserver#27]
Hi,

is it possible to add the Raumfeld Devices maually by ip instead of discovering?
Reason:
My PC is connected to a different subnet so discovering is not working.
Your raumserver was great to use for that, too bad it is discontinued...
Easy to control via curl...

Regards
Sören

**Comment by ChriD** [comment]
> is it possible to add the Raumfeld Devices maually by ip instead of discovering?

It would be possible to add a basic ip in the settings for the host (the devices are stored on the host, so no need for discovering again). But in fact ssdp or bonjour discovery should work well. (see next answer)

> My PC is connected to a different subnet so discovering is not working.

Can you specify this? Do you have 2 network cards and both are connected (have a valid ip)?
This type of setup should work for the node.raumserver because it does discovery on all network adapters with a valid ip. If this does not work its a bug and i have to investigate that. 

> Your raumserver was great to use for that, too bad it is discontinued...
> Easy to control via curl...

I do not have the time to develop the raumserver and node-raumserver both.
In fact node-raumserver is the same as raumserver (a little but slower but much more stable)
So if you were good with raumserver, the node-raumserver should be good too?!

**Comment by ChriD** [comment]
@smindorf 
Hi, Can you please provide mi with the answers for the questions i asked?
Furthr i have added a config file so you may add a fixed ip for the host.
You have to start the node-raumserver  with `raumserver.js` instead of `test.js`

**Comment by smindorf** [comment]
Hi Chris,
sorry for the delay. Bit I've already explained it on a private mail, because I think I've questions which are not the right place to discuss it here. (But no answer..)

But to your question:
I've connected the raumfeld controller to a special WLAN where all my multimediadevices are connected to. The all connections to that WLAN are routed over the firewall.

I' m not really firm with node so I installed all dependencies to the folder node_modules, deleted the 
folders started with node-raum{kernel,server}, and cloned both from git-master.

If I now enter the IP address into the config of node-raumserver and start it out of the folder:
```
cd node_modules/node-raumserver
node raumserver.js
```

I get the following error:
```
smindorf@NB13923:~/node_modules/node-raumserver⟫ nodejs raumserver.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/smindorf/node_modules/node-raumserver/raumserver.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
1 smindorf@NB13923:~/node_modules/node-raumserver⟫
```

Kind regards,
Soeren

**Comment by smindorf** [comment]
One additional question:

what software must be installed on the raumfeld devices?

Regards,
Soeren

**Comment by ChriD** [comment]
> sorry for the delay. Bit I've already explained it on a private mail, because I think I've questions which are not the right place to discuss it here. (But no answer..)  

Hmm. I did not get any mail. maybe the spam/jam filter soaked it up

> I' m not really firm with node so I installed all dependencies to the folder node_modules, deleted the
> folders started with node-raum{kernel,server}, and cloned both from git-master.

in fact the only thing you have to do is to create a folder for the raumserver and then do `npm install node-raumserver` (command line in that folder). This will get the newest version of the node-raumserver and kernel and all it dependencies, either the config dependency. The error message you get points out, that the dependencies are not installed correctly.

> I've connected the raumfeld controller to a special WLAN where all my multimediadevices are connected to. The all connections to that WLAN are routed over the firewall.


node-raumserver uses bonjour and/or ssdp discovery to find the raumfeld host.
I think your firewall may block those ssdp / bonjour packets. But with the fixed IP you should be fine if your firewall allowes UPNP packets


> what software must be installed on the raumfeld devices?
Actual firmwares are recommended. Maybe old ones work too but not with the whole functionality.
In fact standard requests / command should work down to a very old firmware

**Comment by smindorf** [comment]
Hi Chris,
I do as you wrote but without success.

```smindorf@NB13923:~/raumserver/node_modules/node-raumserver⟫ nodejs raumserver.js 
info: [Raumserver] Welcome to raumserver v0.0.8 (raumkernel v1.1.5)
verbose: [Raumserver] Setting up raumkernel
verbose: [Raumkernel] Setting up manager disposer
verbose: [ManagerDisposer] Creating device manager
verbose: [ManagerDisposer] Creating zone manager
verbose: [ManagerDisposer] Creating media list manager
verbose: [ManagerDisposer] Creating trigger manager
verbose: [Raumkernel] Creating controllers
debug: [Raumkernel] Bind manager events
info: [DeviceManager] Start searching for raumfeld host via bonjour
verbose: [Raumserver] Starting HTTP server to receive requests
verbose: [Raumserver] Starting bonjour server for advertising
verbose: [Raumserver] Raumserver listening on port 8080
warn: [DeviceManager] Raumfeld host not found. Retrying discovery with ssdp!
info: [DeviceManager] Start searching for raumfeld host vis ssdp
warn: [DeviceManager] Raumfeld host not found. Retrying discovery with bonjour!
info: [DeviceManager] Start searching for raumfeld host via bonjour
```

```
130 smindorf@NB13923:~/raumserver/node_modules/node-raumserver⟫ ping 192.168.120.14
PING 192.168.120.14 (192.168.120.14) 56(84) bytes of data.
64 bytes from 192.168.120.14: icmp_seq=1 ttl=63 time=5.55 ms

--- 192.168.120.14 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.553/5.553/5.553/0.000 ms
smindorf@NB13923:~/raumserver/node_modules/node-raumserver⟫ ssh root@192.168.120.14
Welcome to Raumfeld (Release:1.62)
root@connector:~ $ 
```

```default.js
{
    "raumserver": {
        "port" : 8080
    },
    "raumfeld": {   
        "raumfeldHost"              : "192.168.120.14", // 0.0.0.0 = autodetect
        "raumfeldHostRequestPort"   : 47365, 
        "raumfeldManufacturerId"    : "Raumfeld GmbH",
        "raumfeldVirtualMediaPlayerModelDescription" : "Virtual Media Player",
        "alivePingerIntervall"      : 2500,
        "ssdpDiscovertimeout"       : 5000,
        "bonjourDiscoverTimeout"    : 3000,
        "uriMetaDataTemplateFile"   : "lib/setUriMetadata.template",
        "rendererStateTriggerConfirmationTimout": 3500,
        "zoneTriggerConfirmationTimout": 6000
    }
}
```

Regards,
Soeren

**Comment by ChriD** [comment]
Hmm... It looks like the config file is not found. I,ll check this out this week.

**Comment by ChriD** [comment]
@smindorf 
Well. It was a bug. i got all the information from the config file except the hostIp.
I have fixed it in the git repo.
 An updated npm version will be published later, so you may replace the` raumserver.js` file from the git in your installation meanwhile and it should work!
