### ISSUE TITLE
node-raumserver direkt auf einem Raumfeld-Gerät installieren

### ISSUE THREAD

**Issue by steff75** [ChriD/node-raumserver#29]
Hallo!

Wird es eigentlich auch möglich sein, den neuen node-raumserver direkt auf einem Raumfeld-Gerät zu installieren?

Hintergrund ist folgender: Ich möchte Raumfeld über meinen Echo Dot in Verbindung mit dem AutoVoice Skill (Tasker Plugin für Android) steuern. Da wäre es gut wenn der Raumserver auf einem Gerät läuft, welches eh 24/7 eingeschaltet ist.

Außer meinem Raumfeld One S sind das bei mir nur eine Synology Diskstation 211j und diverse Android Geräte. Für das Synology gibt es für den Prozessor nur ein ganz veraltetes node.js Paket, 0.10 glaube ich.
In Android kann man mit Termux das node.js Paket installieren,, allerdings auch nur Version 6.10.2.

Vielen Dank!
Stefan

**Comment by ChriD** [comment]
Hi, ja ist geplant, würde auch schon laufen wenn man die node armv7 binaries auf die devices kopiert. Der installer dauert noch zum entwickeln.

Kannst du docker auf deinem synology nas installieren? Für docker gäbs einen aktuellen node

**Comment by steff75** [comment]
Schön, hört sich gut an :)

Docker wird für meine DS211j nicht angeboten. Ich denke, da reicht die Leistung nicht aus. Ich hatte kürzlich mal das testweise das openhab2 Paket installiert und danach war das Gerät praktisch nicht mehr ansprechbar. Aber als Medienserver und Lösung für Backups ist das Gerät völlig ausreichend.

**Comment by steff75** [comment]
Ich habe das eben einmal getestet und Node.js im Ordner /opt/node installiert. Anschließend hatte ich mit npm den node-raumserver im /tmp Ordner zum Ausprobieren installiert.

Dann mit node die test.js gestartet und es läuft. Im Browser konnte ich dann mit deiner TestGUI erfolgreich verschiedene Befehle ausprobieren.

Wegen meiner bescheidenen Linuxkenntnisse warte ich ich aber noch lieber auf deinen Release. Ich habe nämlich nicht so die Ahnung, wo im Dateisystem der beste Ort für die Installation des Moduls ist und wie man ein Autostart Skript richtig anlegt ;-)

**Comment by ChriD** [comment]
> Wegen meiner bescheidenen Linuxkenntnisse warte ich ich aber noch lieber auf deinen Release. Ich habe nämlich nicht so die Ahnung, wo im Dateisystem der beste Ort für die Installation des Moduls ist und wie man ein Autostart Skript richtig anlegt ;-)

Nun, da geht es mir ehrlich gesagt auch so.
