### ISSUE TITLE
Node-Raumserver Lautstärke

### ISSUE THREAD

**Issue by Holliwyoming** [ChriD/node-raumserver#32]
Hallo 
Ich habe node-raumserver erfolgreich installiert
habe aber Probleme mit der Lautstärke
Folgendes wird in einem Script abgesetzt
on({id: "javascript.0.Radio_Lauter", val: true}, function(dp) {
   var url10 = "http://192.168.178.64:8080/raumserver/controller/volumeUp?value=5&id=Kueche";
   request(url10);
   setState(dp.id, false);
});
bekomme folgende Fehlermeldung zurück

debug: [DeviceManager] Media renderer for id : Kueche found
debug: [Request.volumeUp] Calling action 'volumeUp' for renderer Kueche
debug: [MediaRenderer|Kueche] Call GetVolume from Kueche
debug: [MediaRenderer|Kueche] Result of GetVolume for Kueche is {"CurrentVolume":"26"}
(node:2631) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): ReferenceError: _data is not defined

**Comment by Holliwyoming** [comment]
on({id: "javascript.0.Radio_Mute_Off", val: true}, function(dp) {
   var url13 = "http://192.168.178.64:8080/raumserver/controller/unMute?id=Kueche";
   request(url13);
   setState("Radio_Mute_Off", false);
});
Dieser Befehl funktioniert einwandfrei

**Comment by ChriD** [comment]
Thanks for thinfo! That is a bug. I'll fix it this week

**Comment by ChriD** [comment]
Fixed in 0.0.9. you may use npm update to get the newest package

**Comment by Holliwyoming** [comment]
Hi ChriD
It works well
Thanks
