### ISSUE TITLE
Ein-/Ausschalten (enterManualStanby/leaveStandby)

### ISSUE THREAD

**Issue by Adrian01** [ChriD/node-raumserver#33]
Hallo Chris,

Ich habe heute mal wieder den node Raumserver installiert und wollte alles wie zuvor in Betrieb nehmen, dabei ist mir aufgefallen das wenn ich folgendes request nutze: "/raumserver/controller/enterAutomaticStandby?id=Bad" alle Lautsprecher ausgeschalten werden statt nur der der sich im Bad befindet, das gleiche gilt auch fürs einschalten.

Gruß, Adrian

**Comment by ChriD** [comment]
Probier mal `&scope=room` hinzuzufügen. Also `/raumserver/controller/enterAutomaticStandby?id=Bad&scope=room`
Ansonsten möcht er nämlich alle Räume in der Zone in wessen der Raum 'Bad' drinnen ist in den Standby schalten.
Ich schau trotzdem auch kurz drüber obs hier vielleicht noch ein Bug ist

**Comment by Adrian01** [comment]
Alles klar, werde es heute Abend testen und gebe dir dann Bescheid. 

Gruß, Adrian

**Comment by Adrian01** [comment]
Also ich habe es versucht klappt einwandfrei so ;) Danke für den Tipp.

Aber ein Problem hab ich noch, und zwar bin ich nicht mehr ganz so fit in Sachen Linux etc. ich habe den Raumserver auf einem Raspi laufen und habe dort auch screen installiert aber auch wenn ich den Raumserver im screen starte funktioniert dieser nicht mehr nach dem beenden der Konsole, kannst du mir eventuell sagen wie er bei dir im Hintergrund weiterläuft? mache ich irgend einen Fehler?

Gruß, Adrian

**Comment by ChriD** [comment]
Bei mir läuft er nicht im hintergrund. bei mir läuft er auf einem Raumfeld gerät.
Ich kenne 'screen' nicht und bin auch kein großer linux prophet aber  guck mal hier:
http://stackoverflow.com/questions/12701259/how-to-make-a-node-js-application-run-permanently

**Comment by melksem** [comment]
Hi,

Morgen kann ich dir meine Scripte zur Verfügung stellen. 

Marco

**Comment by Adrian01** [comment]
Danke das wäre super ;)

Gruß, Adrian

**Comment by Adrian01** [comment]
Jetzt habe ich mir noch ein weiteres Tool installiert das ich benötige und den Pi nochmals vorher platt gemacht, diesmal habe ich das andere zuerst installiert und bekomme nun folgende Meldung beim versuch den Raumserver zu installieren:

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! Linux 4.9.24-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-raumserver"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /home/pi/node_modules/dorita980
npm ERR! code EISGIT

npm ERR! git /home/pi/node_modules/dorita980: Appears to be a git repo or submodule.
npm ERR! git     /home/pi/node_modules/dorita980
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-13T08_53_09_197Z-debug.log

Weiß jemand was genau ich jetzt machen soll?

Danke im vorraus

Gruß, Adrian

**Comment by melksem** [comment]
Aaaalso, den funktionierenden node-raumserver auf dem Pi3 hab ich so installiert:

```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt install nodejs
mkdir raumfeld
cd raumfeld/
npm install node-raumserver

```

Das Startscript ist dieses:

```
$ cat /etc/init.d/Raumserver
#! /bin/sh
# /etc/init.d/Raumserver

### BEGIN INIT INFO
# Provides:          test
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raumserver initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
   start)
    echo "Starting Raumserver"
    # run application you want to start
    #node /home/pi/test.js > /home/pi/test.log
    sudo -u openhabian /usr/bin/node /home/openhabian/raumfeld/node_modules/node-raumserver/raumserver.js > /etc/raumserver/log/raumserver.log 2>&1 &
   ;;
   stop)
    echo "Stopping Raumserver"
    # kill application you want to stop
    killall -9 node
    # Not a great approach for running
    # multiple node instances
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

```

Da musst Du aufpassen, weil sich irgendwo das "test.js" in "raumserver.js" geändert hat. Und das klappt nur, wenn es die einige NodeJS Anwendung ist wegen des "killall".

Ggf. muss man den Nutzer fürs "sudo" noch anpassen, bei mir ist das node-raumserver halt unter "openhabian" installiert.

Aktiviert wird der Dienst dann mit

```
sudo chmod +x /etc/init.d/Raumserver
sudo update-rc.d Raumserver defaults
```

Und weil es hin und wieder "out of memory" errors gab nach einer gewissen Zeit, wird der raumserver halt regelmäßig neu gestartet per cron aus root:

```
$ sudo crontab -l
59 * * * * /etc/init.d/Raumserver restart
```

Ich hoffe, das hilft weiter.

**Comment by ChriD** [comment]
@melksem
Out of memory? Kannst du mir da mehr infos geben? Eventuell in einem neuen issue?

**Comment by melksem** [comment]
Anfangs kam das mal, ich hab den regelmäßigen Restart nun mal deaktiviert, es läuft jetzt seit 24h problemlos. Falls sich doch was ändert, gebe ich Bescheid.

**Comment by ChriD** [comment]
Ja bitte! Wär blöd wenns da ein Problem gibt
