### ISSUE TITLE
Installation PC / SuSE Leap 42.2

### ISSUE THREAD

**Issue by feseidel** [ChriD/node-raumserver#34]
Hallo,

ich versuche, den node-raumserver auf meinem Atom-PC mit SuSE Leap 42.2 zu installieren. node ist aktuell und läuft (hm-manager, eine andere node-Anwendung funktioniert):
> node --version
v8.1.2

Ich habe node-raumserver per npm istalliert in
/usr/local/lib/node_modules/node-raumserver

Dann möchte ich node-raumserver starten. Das sollte so gehen, oder?
> node /usr/local/lib/node_modules/node-raumserver/raumserver.js

Doch jetzt bekomme ich folgenden Fehler:

> module.js:487
>    throw err;
>    ^
>
> Error: Cannot find module 'query-string'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/node-raumserver/lib/lib.raumserver.js:3:21)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)

Kannst Du mir helfen?

Gruß,
Frank

**Comment by ChriD** [comment]
Hi,

probier mal das modul 'query-string' zu installieren.
also `npm install query-string`

**Comment by feseidel** [comment]
Hi,

ah, okay, dem fehlt das Paket. Hatte ich nicht verstanden.

Nach dem install ging es weiter - zum nächsten fehlenden Paket. Ich habe dann noch installiert:

npm install elementtree
npm install concat-stream
npm install ip
npm install debug

Jetzt startet da was - ich schaue mal ...

Danke Dir, ChriD!
Gruß,
Frank

**Comment by ChriD** [comment]
Hmm.. Eigentlich sollte er das alles mitinstallieren wenn du` npm install node-raumserver` machst
Naja... Muss ich prüfen

**Comment by feseidel** [comment]
Hi,

daskönnte damit zusammenhängen, dass ein uraltes npm hier irgendwie dazwischenhaut. npm -v gibt 2.15.11 als Version zurück.

Ich habe in einer virtuellen Maschine node neu installiert (8.1.3 als linux binaries) undbekomme dann bei npm -v 5.0.3 zurück. Jetzt habe ich auch hier per npm install node-raumserver installiert und es läuft direkt.

Vielleicht hilft das weiter ...

Gruß,
Frank

**Comment by feseidel** [comment]
Hi,

ich hatte node per yast (Paketverawltung von SuSE installiert. Das war Version 4 irgendwas - also zu alt. Dann habe ich manuell 8.1.2 installiert, aber den mit yast installierten npm wurde weiter benutzt. Ich habe jetzt node mit npm per yast deinstalliert. Jetzt wird auch npm in der Version 5.0.3 verwendet. Nun habe ich node-raumserver entfernt und per npm neu installiert. Läuft sofort - und jetzt habe ich im module-Verzeichnis jede Menge (!!!) Module. Also Problem gelöst.

Allerdings bekomme ich beim Start noch eine Fehlermeldung:

info: [Raumserver] Welcome to raumserver v0.0.9 (raumkernel v1.1.6)
verbose: [Raumserver] Setting up raumkernel
verbose: [Raumkernel] Setting up manager disposer
verbose: [ManagerDisposer] Creating device manager
verbose: [ManagerDisposer] Creating zone manager
verbose: [ManagerDisposer] Creating media list manager
verbose: [ManagerDisposer] Creating trigger manager
verbose: [Raumkernel] Creating controllers
debug: [Raumkernel] Bind manager events
info: [DeviceManager] Start searching for raumfeld host via bonjour
verbose: [Raumserver] Starting HTTP server to receive requests
verbose: [Raumserver] Starting bonjour server for advertising
verbose: [Raumserver] Raumserver listening on port 8989
error: uncaughtException: ENOENT: no such file or directory, open 'logs/app.2017-06-29-2137.log' date=Thu Jun 29 2017 23:37:34 GMT+020
0 (CEST), pid=5689, uid=0, gid=0, cwd=/root, execPath=/downloads/local_Software/node.js/node-v8.1.3-linux-x64/bin/node, version=v8.1.3, argv=[/downloads/local_Software/node.js/node-v8.1.3-linux-x64/bin/node, /usr/local/lib/node_modules/node-raumserver/raumserver.js], rss=52572160, heapTotal=34082816, heapUsed=20613960, external=469952, loadavg=[0.166015625, 0.0771484375, 0.01708984375], uptime=1243404
Error: ENOENT: no such file or directory, open 'logs/app.2017-06-29-2137.log'
verbose: [DeviceManager] Found Bonjour Service on:xxx.xxx.xxx.xxx

node-raumserver läuft aber, ich komme per Firefox auf die Webseite und ich kann auch Befehle wie volume absetzen ...

Gruß,
Frank

**Comment by ChriD** [comment]
Hi, probier mal ein "logs" Verzeichnis im Ordner zu erstellen
