### ISSUE TITLE
listen, push or notify

### ISSUE THREAD

**Issue by gamade** [ChriD/node-raumserver#45]
Hallo,

ich bastle gerade an einem Gateway zum smarthomeNG projekt. 
Die Steuerung läuft soweit gut und stabil über http requests. An dieser Stelle vielen Dank für die Mühen und Implementierung!

Jetzt geht es darum, möglichst in Echtzeit "Systemänderungen" mitzubekommen. Zwar kann man über getRendererState zyklisch pollen, aber das ist nicht gerade schick. 

Im Konsolen-Output sieht man sehr schön, dass Änderungen dem Server bekannt werden. Die Frage ist nur, wie man sich auf diesen "Livestream" über http dranhängen kann? Timeouts könnten über keep-alive Messages oder reconnects gelöst werden. Es wäre gut, wenn der RendererState "gepusht" würde, sobald sich ein Wert ändert. Auf Seite des Gateways würde ich dann den json block durch den parser lassen und die entsprechenden Variablen im SmartHome System updaten. 

Was meinst Du?

**Comment by gamade** [comment]
In den Log Dateien vom Raumserver sehe ich die updateId. Nehme ich diese Nummer in den folgenden Request mit rein, so blockiert die Anfrage bis eine Änderung auftritt und schickt dann den Response. Zunächst so, wie es sein soll. 
Auf der Server Konsole sehe ich, dass eine neue updateId vergeben wurde:

> debug: [Request.getRendererState] Adding response header for request 'getRendererState' -> updateId : 106729

aber im "getRendererState" Response sehe ich diese nicht im json Paket und kann somit keinen neuen request auf die neue Nummer absetzen. 

Übersehe ich noch was?

**Comment by ChriD** [comment]
Jup. Die updateId steht im header des http responses

**Comment by gamade** [comment]
Habs im header gefunden. Funktioniert soweit... danke!
