### ISSUE TITLE
Change Input on Soundbar/Sounddeck (TV,AUX,OPT)

### ISSUE THREAD

**Issue by alexstern84** [ChriD/node-raumserver#46]
I'm looking for a possibility to switch the Input for the Sounddeck/Soundbar device.

This Input can be changed using the app, and I want to replace the raumfeld remote with my harmony hub, which at the moment can only switch on my sounddeck und switch off my sounddeck, but i still need to switch the channel using raumfeld remote.

As far as i've seen in the "old" issues ChriD don't have this device that's why he can not check if it is possible. But if you tell me what i need to check, or to trace just let me now and i will try that :-)

Thx a lot

Regards
Alex

**Comment by ChriD** [comment]
Hi Alex,

There is a request where you can set device settings, but i am not sure if the switch of the input is a device setting on the soundbar or if it is any other special request.
In fact you may sniff the network what is happening when you change the input. If it is a "DeviceSetting" command, then node-raumserver should be capable of doing this right now. If its any other command i will have to implement it.

There are some issues on the old raumserver whcih may help you, but i think you found it already
https://github.com/ChriD/Raumserver/issues/60
https://github.com/ChriD/Raumserver/issues/42

**Comment by alexstern84** [comment]
Hi ChriD

i can see the following urls send to my sounddeck:

HDMI:
http://192.168.178.109:47365/ffffffff-a529-9c04-ffff-ffffa5299c04/SetPlayerSetting?udn=uuid%3Af7225ab7-3ad5-4c49-9bd0-9d6aaa3db52e&name=TV%20Source%20Select&value=TV_ARC

Optical In:
http://192.168.178.109:47365/ffffffff-a529-9c04-ffff-ffffa5299c04/SetPlayerSetting?udn=uuid%3Af7225ab7-3ad5-4c49-9bd0-9d6aaa3db52e&name=TV%20Source%20Select&value=OpticalIn

Aux:
http://192.168.178.109:47365/ffffffff-a529-9c04-ffff-ffffa5299c04/SetPlayerSetting?udn=uuid%3Af7225ab7-3ad5-4c49-9bd0-9d6aaa3db52e&name=TV%20Source%20Select&value=LineIn

I'm not sure if this is a DeviceSetting now in Raumserver.

Thx & Regards
Alex

**Comment by ChriD** [comment]
Hi Alex, Thanks for sniffing!

No it is not the DeviceSetting. But "SetPlayerSetting" it seems to be only a request to the host like creating zones so it should be no problem for me to implement it.

**Comment by ChriD** [comment]
@alexstern84 
i found out that i have doxumented the Source select on SetDeviceSettings
So you may already change the Source of Your Sounbar by call ing the SetDeviceSetting request with "Source Select" as key and "LineIn", "OpticalIn", "TV_ARC" or "Raumfeld" as values.

May you try it out please?

**Comment by alexstern84** [comment]
@ChriD 
couldn't find the documentation about SetDeviceSettings. Tried the following without success:
{"requestUrl":"/raumserver/controller/SetDeviceSetting?Source%20Select=OpticalIn&id=Wohnzimmer","action":"SetDeviceSetting","error":true,"msg":"Unknown action","data":{}}

**Comment by alexstern84** [comment]
@ChriD 
could you please help me to find the error? :-)

**Comment by ChriD** [comment]
"SetDeviceSettings" instead "SetDeviceSetting" ?

**Comment by alexstern84** [comment]
Same error with SetDeviceSettings :(
{"requestUrl":"/raumserver/controller/SetDeviceSettings?Source%20Select=OpticalIn&id=Wohnzimmer","action":"SetDeviceSettings","error":true,"msg":"Unknown action","data":{}}

**Comment by ChriD** [comment]
Are you sure aou are using the latest node-raumserver?
On my test the request works quite well. Okay i get another error but this is because i do not have a soundbar attached to "Wohnzimmer" but the request is found
http://ip:8080/raumserver/controller/SetDeviceSetting?key=Source%20Select&value=OpticalIn&id=Wohnzimmer

`{"requestUrl":"/raumserver/controller/SetDeviceSetting?key=Source%20Select&value=OpticalIn&id=K%C3%BCche","action":"SetDeviceSetting","error":true,"msg":"Action was rejected","data":{"errorMessage":"Error: Cannot find requested setting in exported alsa controls. (404)","errorData":null}}`

**Comment by alexstern84** [comment]
Hi ChriD,

thx for the update. I am using the following version:
{"requestUrl":"/raumserver/data/getVersion","action":"getVersion","error":false,"msg":"","data":{"raumkernelLib":"1.1.9","raumserverLib":"0.0.10"}}

is there a newer available?

**Comment by alexstern84** [comment]
that's what i see in the log:

verbose: [Raumserver] Request received: GET /raumserver/controller/SetDeviceSetting?key=Source%20Select&value=OpticalIn&id=Wohnzimmer
debug: [Raumserver] Request to raumserver recognized: /raumserver/controller/SetDeviceSetting?key=Source%20Select&value=OpticalIn&id=Wohnzimmer
error: [Raumserver] Error creating request for action 'SetDeviceSetting': Cannot find module './requestHandlers/lib.request.SetDeviceSetting' | stack: Error: Cannot find module './requestHandlers/lib.request.SetDeviceSetting'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.newFromAction (/home/pi/raumfeld/node_modules/node-raumserver/lib/lib.base.request.js:21:31)
    at Raumserver.handleRequestObject (/home/pi/raumfeld/node_modules/node-raumserver/lib/lib.raumserver.js:124:34)
    at Raumserver.requestReceived (/home/pi/raumfeld/node_modules/node-raumserver/lib/lib.raumserver.js:106:22)
    at Server.<anonymous> (/home/pi/raumfeld/node_modules/node-raumserver/lib/lib.raumserver.js:80:26)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:194:7)
    at parserOnIncoming (_http_server.js:563:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
error: [Raumserver] Action 'SetDeviceSetting' is not a valid action!
error: [Raumserver] Request was rejected because of unknown action
verbose: [Raumserver] Request received: GET /favicon.ico
error: [Raumserver] Request was rejected because unknown path

**Comment by ChriD** [comment]
The other requests work?
If they work it seems that the request script is not there in the requestHandlers folder. You may copy it from the repo to the local folder on your drive

**Comment by alexstern84** [comment]
Hi ChriD,

working like a charm, when we use the right URL name ;-) of course it is case sensitive.....

http://ip:8080/raumserver/controller/setDeviceSetting?key=Source%20Select&value=OpticalIn&id=Wohnzimmer

{"requestUrl":"/raumserver/controller/setDeviceSetting?key=Source%20Select&value=OpticalIn&id=Wohnzimmer","action":"setDeviceSetting","error":false,"msg":"","data":{"udn":"uuid:f7225ab7-3ad5-4c49-9bd0-9d6aaa3db52e"}}

thx for help!

**Comment by ChriD** [comment]
Perfect :)
