### ISSUE TITLE
change port

### ISSUE THREAD

**Issue by kaloschke** [ChriD/node-raumserver#52]
Hi,

i have changed the port in config.js, but the server starts with 8080.
Is there another location to change this?

Greetings kaloschke

**Comment by ChriD** [comment]
I should be ok. I'll check it!

**Comment by kaloschke** [comment]
Thank you

**Comment by ChriD** [comment]
i can not reoroduce the issue. How do you start the node-raumserver? Maybe the config file is not found

**Comment by gahujipo** [comment]
I found out some weird behavior when i tried to create the log directory. This directory has to be in the same current working directory where you launch the command "node raumserver.js". Maybe it is the same case with the config directory. So maybe you didn't change to the directory e.g. /etc/raumserver and started with the command "node raumserver.js" but started e.g. "node /etc/raumserver/raumserver.js"?

**Comment by ChriD** [comment]
Yea i admit that the start is a little bit stupid, i have to find a better solution. But for now  if you install the node raumserver like that:
```
npm install node-raumserver
cd node_modules/node-raumserver
npm start
```
it will use the condig file

**Comment by kaloschke** [comment]
Hi,
that is working for me too. I don't remember excactly, but I have used another start procedure.
Thank you very much.
