### ISSUE TITLE
Getrenderstate

### ISSUE THREAD

**Issue by abercrombie1892** [ChriD/node-raumserver#56]
Hallo,

Erstmal ein großes Lob für den raumserver. Ich hoffe ihr könnt mir evtl. weiterhelfen.

Ich nutze fhem und würde dort gerne den Transportstate angezeigt bekommen um meinen Receiver mit einzuschalten. 

Ich weiß leider nicht wie ich das dort einpflegen kann. Das mit der updateId hab ich schon festgestellt, aber die ändert sich ja bei jeder Änderung.
Im Moment läuft das nicht über httpmod, ist aber nicht wirklich zufriedenstellend.

Mit freundlichen Grüßen

**Comment by ChriD** [comment]
naja... Das nennt sich long polling. Du musst einen neuen request mit der ID starten die zurück kam.
