### ISSUE TITLE
update node raumserver

### ISSUE THREAD

**Issue by Spassat35i** [ChriD/node-raumserver#57]
Hi,

I'm not realy sure if this is a bug or I just did somthing wrong. but today I tried to upgrade the Node-raumserver to the latest revision but it ends with:

pi@OpenHab:~ $ sudo apt-get upgrade node-raumserver
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... **E: Paket node-raumserver kann nicht gefunden werden.**

does someone know what went wrong?

Thank you very much in advance.

Marcel

**Comment by ChriD** [comment]
I am not sure what are you trying to do?
node-raumserver is based on nodeJs and therfore nodeJs is needed and it can be installed with npm
There is no package for individual linux distributions

**Comment by Spassat35i** [comment]
Thanks for your quick replay. I'm not an expert on Linux. But I running jessy on a pi3 and use node-raumserver with openHAB. Node Raum server is version 0.0.10 and I would like to go with your latest release. Even nodeJs is running on 7.10.xxx if I remember correctly. I have learned a lot during the last year but not had to deal a lot with npm. Is there a command for upgrading the existing version or should I do a full installation?

Sorry for all that questions.

Marcel

**Comment by ChriD** [comment]
you only have to go to the directory where node-raumserver ist installed (wher you first installed it) and then type `npm update` in the console. that should work
