### ISSUE TITLE
Docker warn: [DeviceManager] Raumfeld host not found

### ISSUE THREAD

**Issue by Jenser-72** [ChriD/node-raumserver#60]
Hallo,
ich habe auf meiner Synology DS415+ unter Docker den ChriD Raumserver laufen, doch leider bekomme ich 
im Protokoll die folgende Fehlermeldung:
warn: [DeviceManager] Raumfeld host not found
und wenn ich über http://192.168.120.3:8585/raumserver/controller/leaveStandby?id=Schlafzimmer
den Lautsprecher abschalten möchte funktioniert das nicht und ich bekomme folgende Fehlermeldung:

requestUrl | "/raumserver/controller/leaveStandby?id=Schlafzimmer"
-- | --
action | "leaveStandby"
error | true
msg | "Action was rejected"
data |  
errorMessage | "Error: VirtualMediaRenderer for id 'Schlafzimmer' not found"
errorData | null

Am Docker Container kann ich doch nichts einstellen um die IP manuell mitzugeben oder? 
Ich hoffe ihr könnt mir einen Tipp geben. Auf den Geräten ist die aktuelle Firmware 2.3 installiert
Oder gibt es auch eine Möglichkeit den Raumfeld Server auf einer VM mit Windows 10 laufen zu lassen?

Viele Grüße 
Jens

**Comment by ChriD** [comment]
Das
net=--host 
hast du beim Docker vontainer angegeben oder?

**Comment by gahujipo** [comment]
bei mir funktioniert der Befehl (ohne Docker) aber auch nicht. Er funktioniert nur wenn man den Speaker aus dem ECO-Modus aufwecken möchte. Siehe dazu auch [hier](https://github.com/gahujipo/node-raumserver-wiki/blob/master/Use/Standby.md)

**Comment by Jenser-72** [comment]
Ich hatte das mit net=--host gelesen, aber nichts gefunden wo ich das beim Docker Container eintragen kann. Es gibt nur eine Registerkarte "Volume" wo ich Dateien und Ordner anlegen könnte dann eine Registerkarte "Links", "Port Einstellungen" und "Umwelt" dort ist der PATH : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin eingetragen, NODE Version 8.9.4, YARN_VERSION 1.3.2 
Wenn der Docker Container läuft steht da Ausführungsbefehl "npm start" lässt sich aber nicht verändern. 
Den ECO Modus hatte ich bei den Lautsprechern deaktiviert. 
Vielen Dank Euch schonmal

**Comment by ChriD** [comment]
Das mit dem net auf host einstellen muss gemacht werden. Sonst ist der docker container nicht im netzwerk. Ich bin gerade nicht zuhause. Kann dir dann nachsehen wo man das einstellt.

**Comment by Jenser-72** [comment]
Super, das wäre sehr schön ... ich habe schon mit Google gesucht aber leider nichts gefunden, außer dass es schon jemand mit Docker auf einer Synology DS laufen hat.

**Comment by Jenser-72** [comment]
Danke Christian,
ich habe den Fehler gefunden und es läuft *freu 
Auf der Synology DS muss unter "Abbild" der Container ausgewählt werden und dann beim ersten Starten auf erweiterte Einstellungen  bei Netzwerk unten bei "Dasselbe Netzwerk wie Host verwenden" ein Hacken gesetzt und nicht wie sonst üblich "bridge" eingestellt werden. 
Vielen Dank und viele Grüße
Jens

**Comment by ChriD** [comment]
Perfekt! Freut mich!
