### ISSUE TITLE
How to get Album or Artist list via http?

### ISSUE THREAD

**Issue by guidobonerz** [ChriD/node-raumserver#67]
How to get Album or Artist list via http?
Is that possible?
Best regards

**Comment by ChriD** [comment]
The 'getRendererState' should return a json string/Object which includes a subobject  'mediaItem'

**Comment by guidobonerz** [comment]
Hmm, i have not yet tested it, but are you sure that 'getRenderState' is what i asked for?
I wanted to get a list of albums or artists in my database?

**Comment by ChriD** [comment]
ah ok you do want to have a content browser.
It possible with the kernel:
https://github.com/ChriD/node-raumkernel/blob/master/sample_contentBrowser.js

but there is no request for that.
But it would be no big deal to create a contentBrowse request

**Comment by ChriD** [comment]
@guidobonerz 
I have added a request for browsing the content. You have to start with id "0". This is the root
e.g.:
http://localhost:8080/raumserver/controller/getMediaList?id=0

It will return you a JSON string with the content. In fact it will be "My Music", "Playlists" aso. on the root level. Each sublevel willhave another id which is listed in the response. So you can easaly run through the tree.

**Comment by guidobonerz** [comment]
Hi, thank you for your quick response ;-)
I will check it.
