### ISSUE TITLE
nodeJS executable looking for wrong path

### ISSUE THREAD

**Issue by JimboJones3101** [ChriD/node-raumserver#73]
Hi there,

based on issue #12 the the corresponding stackoverflow-link I'm trying to create an executable which will run the raumserver on startup, which seems to be working as of now. 

The executable which lies in `/etc/init.d` runs the nodeJS app located in `/home/openhabian/node_modules/node-raumserver/raumserver.js`. Unfortunately the running app is looking for the configuration in it's current path and I'm getting the Warning `WARNING: No configurations found in configuration directory:/etc/init.d/config` which leads to an error as port 8080 is already blocked. My config (located in `/home/openhabian/node_modules/node-raumserver/config`) stated the app to be running under 1337 but as the system doesn't find the folder it automatically runs under 8080.

Is there any way to explicitly stating the full path to the config within the raumserver.js - which probably as of now tries to reference this from it's current location?

Thanks in advance

p.S. I created a stackoverflow issues as I'm not sure if this is an application or rasbian issue. See here [https://stackoverflow.com/questions/53850998/raspbian-node-js-executable-looking-for-wrong-path](url)

**Comment by ChriD** [comment]
The configuration is a 3rd party module.
you may try to change the path of the config file with an environmental var as explained here:
[https://github.com/lorenwest/node-config/wiki/Environment-Variables](https://github.com/lorenwest/node-config/wiki/Environment-Variables)

**Comment by davie2000** [comment]
Why init.d? I have a file called /etc/init/myraumserver.conf with the following content:
```
start on runlevel [2345]
stop on runlevel [!2345]

# respawn the job up to 10 times within a 5 second period.
# If the job exceeds these values, it will be stopped and
# marked as failed.
respawn
respawn limit 10 5
script
  cd /home/davie2000/my-raumserver/node_modules/node-raumserver   
  node raumserver.js
end script
```
If the server fails (whyever) it is automatically started again. Good luck!

**Comment by JimboJones3101** [comment]
> Why init.d? I have a file called /etc/init/myraumserver.conf with the following content:
> 
> ```
> start on runlevel [2345]
> stop on runlevel [!2345]
> 
> # respawn the job up to 10 times within a 5 second period.
> # If the job exceeds these values, it will be stopped and
> # marked as failed.
> respawn
> respawn limit 10 5
> script
>   cd /home/davie2000/my-raumserver/node_modules/node-raumserver   
>   node raumserver.js
> end script
> ```
> If the server fails (whyever) it is automatically started again. Good luck!

To be honest I'm quite new to the whole technology and I wasn't aware that you can do a simple `cd` in these executables. Thus I followed your approach and now - when the RPi starts - it automatically looks for the right config file and runs on the correct port.

Thank you very much, esp. with your patience.

p.S. have a nice xmas time!

**Comment by ChriD** [comment]
Perfekt! Thank's  all for contributing!
