### ISSUE TITLE
Chromecast commands are not executed

### ISSUE THREAD

**Issue by sebou1234** [ChriD/node-raumserver#74]
Hello, first of all, thank you for this great project.
I just installed the raumserver on my Raspberry which also is the server for my Openhab home-automation system. With the raumserver I want to control my Raumfeld Stereo M system.
In general the raumserver seems to work. I can start playlists, stop them, pause them, send the system into standby, etc...
The problems start when streaming music through the chromecast interface of the Raumfeld. As soon i start music via the google play music app and start to stream them on the speakers via chromecast, the raumserver refuses to accept any commands, I can't send the system into standby, can't pause the current track, etc.

In my browser I get following error:

_{"requestUrl":"/raumserver/controller/mute","action":"mute","error":true,"msg":"Action was rejected","data":{"errorMessage":"Error: VirtualMediaRenderer for id '' not found","errorData":null}}_

Is there any solution or workaround for this problem?
Additionally I have to add that I am very very new to programming :)
Thank you very much 
Sebastian

**Comment by ChriD** [comment]
Hi, 
Im no sure how the implementation of chromcast works within raumfeld. 
Are you able to pause or mute the speaker via the RaumfeldApp ?

**Comment by sebou1234** [comment]
Hello, thank you for your reply.

When the music is streamed through the chromecast interface, I can can control the speakers through the RaumfeldApp as usual. I can pause, mute, control the volume, send the speakers into standby, etc. I also the the current track information (title, album cover, current position of the track...)
Only the control through the raumserver doesn't work. 

_getRendererState_ works and I do receive the current track information which is streamed through the chromecast interface.

As soon I stop the stream or change to an RaumfeldApp Playlist , everything is back to normal and the raumserver works again (pause, mute, play, etc).
I have to add that I only have one speaker/one room in my system.

Best Regards
Sebastian

**Comment by ChriD** [comment]
Hmmm. Have you tried to specify the renderer on the request with the appropriate id/name?

**Comment by sebou1234** [comment]
With renderer, do you mean the id at the end of the command? I have tried with and without the id. Both  command work flawlessly as as long the music is not streamed via the chromecast interface.
I tried following commands:
http://[ip]:8080/raumserver/controller/play?id=Wohnzimmer
http://[ip]:8080/raumserver/controller/play

As soon the music is streamed via chromecast, i get the error message I attached in my first post for every "controller" command".

**Comment by ChriD** [comment]
Can you please post the result of getZoneConfig request when chromecast is running?

**Comment by sebou1234** [comment]
This is the result I get wen chromecast is running:

{
  "requestUrl": "/raumserver/data/getZoneConfig",
  "action": "getZoneConfig",
  "error": false,
  "msg": "",
  "data": {
    "zoneConfig": {
      "$": {
        "numRooms": "1",
        "spotifyMode": "multiRoom"
      },
      "unassignedRooms": [
        {
          "room": [
            {
              "$": {
                "name": "Wohnzimmer",
                "udn": "uuid:ac28adf6-fa7a-4e00-9293-ace900a95e72",
                "powerState": "ACTIVE"
              },
              "renderer": [
                {
                  "$": {
                    "udn": "uuid:73b1da32-e61d-4a04-92e5-62c9ce9eda76",
                    "name": "Speaker Wohnzimmer",
                    "googleCast": "active"
                  } } ] } ] } ] } } }


This is the result I get when I stream something via TuneIn, startet from the RaumfeldApp:

{
  "requestUrl": "/raumserver/data/getZoneConfig",
  "action": "getZoneConfig",
  "error": false,
  "msg": "",
  "data": {
    "zoneConfig": {
      "$": {
        "numRooms": "1",
        "spotifyMode": "multiRoom"
      },
      "zones": [
        {
          "zone": [
            {
              "$": {
                "udn": "uuid:5b0269aa-ae3a-4cb8-a455-72015bcf3146",
                "spotifyConnect": "inactive"
              },
              "room": [
                {
                  "$": {
                    "name": "Wohnzimmer",
                    "udn": "uuid:ac28adf6-fa7a-4e00-9293-ace900a95e72",
                    "powerState": "ACTIVE"
                  },
                  "renderer": [
                    {
                      "$": {
                        "udn": "uuid:73b1da32-e61d-4a04-92e5-62c9ce9eda76",
                        "name": "Speaker Wohnzimmer"
                      } } ] } ] } ] } ] } } }


Thank's for your support :)

**Comment by sebou1234** [comment]
Thank you, if this would work I would be completely satisfied with my current setup :)

**Comment by ChriD** [comment]
@sebou1234 
Cany you please try using `&scope=room` when posting the request? It may be that this will work.
So eg.: `http://[ip]:8080/raumserver/controller/play?id=Wohnzimmer&scope=room`

**Comment by sebou1234** [comment]
Hello, did a quick test this morning.
with `&scope=room` some commands works, e.g. mute, unMute, enterManualStandby, volume.
What doesn't work is stop, play, pause.
I am already pretty happy with that. Thank you very much.

One command which also doesn't work is `loadPlaylist`
I entered following request:
`http://192.168.0.131:8080/raumserver/controller/loadPlaylist?id=Wohnzimmer&scope=room&value=Fm4`
I get the Error `loadPlaylist is not allowed to be used with room renderers!`
Is there a walk-around to make this work?

**Comment by sebou1234** [comment]
I just did a few more tests: 
The problem is that I can send the system into Standby when music is streamed via chromecast by adding `&scope=room` but it will stay in the chromecast mode after `leaveStandby` (if I directly again wake them up again).

If the System stays in Standby, the chromecast/googlecast  mode is ended after some minutes. `loadPlaylist` still doesn't work as the speakers stay in the `unassignedRooms`
After using chromecast I need to use the RaumfeldApp as this seems to be the only way to repair this.

**Comment by ChriD** [comment]
> I get the Error `loadPlaylist is not allowed to be used with room renderers!`
> Is there a walk-around to make this work?
Well you may try to use the "createZone" request.  This will bring back the room into a zone and therefore all commands should work again. I am not sure if this works if the chromecast mode is active?!
But you may try!

**Comment by sebou1234** [comment]
Good Morning, just did a quick test: 
This seems to work as a pretty good work-around. 
By sending the "createZone" request, the speakers stop the chromecast stream and are back in the room they should be. Then the requests work as they should :)

Thank you very much for your help and for the Raumserver in general :)
