### ISSUE TITLE
Implementation of TogglePlayPause

### ISSUE THREAD

**Issue by gahujipo** [ChriD/node-raumserver#79]
I'd like to implement a TogglePlayPause feature. I see that I have to create a lib.request.togglePlayPause.js class and call there within runAction() either the pause or play function. How can I get the renderer state there whether it's PLAYING or PAUSED_PLAYBACK? This should be the property which is visible in /raumserver/controller/getRendererState. But how can i get the property there in runAction()? 

Thanks in advance.

**Comment by ChriD** [comment]
The virtual renderer does have a property called "rendereState"
This is an object which should have the "TransportState" proprty (String) which shows the current transport state of the media

e.g.:
`virtualRenderer.rendererState.TransportState`

The available Transport States are  UPNP Standarf:
```
STOPPED,PLAYING, TRANSITIONING, PAUSED_PLAYBACK, NO_MEDIA_PRESENT, ...
```

**Comment by ChriD** [comment]
Thank you for your contribution! I have merged it into the master branch and I'll pull a new version to NPM in the afternoon!

**Comment by ChriD** [comment]
npm is updated
