### ISSUE TITLE
Adding room to spotifyConnect zone

### ISSUE THREAD

**Issue by daninedan** [ChriD/node-raumserver#84]
Hi there...

i would be very greatful for some help understanding an issue I have with zone configuration. I have following zoneConfig:

{"requestUrl":"/raumserver/controller/getZoneConfig","action":"getZoneConfig","error":false,"msg":"","data":{"zoneConfig":{"$":{"numRooms":"4","spotifyMode":"multiRoom"},"zones":[{"zone":[{"$":{"udn":"uuid:9e15f441-24a5-44ee-aa7b-5c8a42208ec2","spotifyConnect":"inactive"},"room":[{"$":{"name":"Kueche","udn":"uuid:0dc493fa-7448-4319-986a-28b89c27f0d7","powerState":"AUTOMATIC_STANDBY"},"renderer":[{"$":{"udn":"uuid:0251254a-629c-45d6-82cf-7359d05de4a1","name":"Speaker Kueche"}}]},{"$":{"name":"Arbeitszimmer","udn":"uuid:6a737fac-fd3f-4de4-bae6-c4c8a7681b63","powerState":"AUTOMATIC_STANDBY"},"renderer":[{"$":{"udn":"uuid:ace52c08-9f45-4242-b9d9-e238df4b1675","name":"Speaker Arbeitszimmer"}}]}]}]}],"unassignedRooms":[{"room":[{"$":{"name":"Wohnzimmer","udn":"uuid:16e6cc43-b4d1-41df-9a1e-0b931aec8bd8","powerState":"ACTIVE"},"renderer":[{"$":{"udn":"uuid:6e0f3e94-f452-425f-bb1e-5d3a93e389b6","name":"Speaker Wohnzimmer"}}]},{"$":{"name":"Schlafzimmer","udn":"uuid:1daf06a1-63a6-4bc0-b23e-41dedc06ac5f","powerState":"ACTIVE"},"renderer":[{"$":{"udn":"uuid:0261a603-58fa-41c4-8c10-ea4cb3790223","name":"Speaker Schlafzimmer"}}]}]}]}}}

I now want to add the speaker "Wohnzimmer" to the zone "spotifyConnect" and I tried the following command:

http://dane-nas:8080/raumserver/controller/addToZone?id=Wohnzimmer&zoneId=spotifyConnect

I get following error:

{"requestUrl":"/raumserver/controller/addToZone?id=Wohnzimmer&zoneId=spotifyConnect","action":"addToZone","error":true,"msg":"Action was rejected","data":{"errorMessage":"Error: Zone for zoneId 'spotifyConnect' not found!","errorData":null}}

Does anyone know why? I do not understand which zoneID to take for "spotifyConnect" if this one is not recognized...

Would be greatful for any help. Thank you!

**Comment by ChriD** [comment]
There is no 'spotifyConnect' zone. 
A Zone in fact does not have a name at all. A zone can only be specified due the rooms which are in the zone
So try following:

`http://dane-nas:8080/raumserver/controller/addToZone?id=Wohnzimmer&zoneId=Kueche`

wherby 'Kueche' can be any room in the zone

**Comment by daninedan** [comment]
Thanks for the fast answer! Works like a charm!
