### ISSUE TITLE
How to install on Raumfeld/Teufel-Device?

### ISSUE THREAD

**Issue by davie2000** [ChriD/node-raumserver#85]
Hi ChriD!

I would like to know if you managed to install node-raumserver directly on a Raumfeld-device in the meanwhile?
Otherwise I will try to install node.js for armv7 on my Connector² to /usr/lib/nodejs via SSH.
Do you have some advice for me where to put - or not to put because of overwrite when updating - the server to?

TiA & greetz
  davie2000

**Comment by ChriD** [comment]
Some time ago i had installed nodeJs an the connector 2. the node-raumserver did its job but the connector2 is not a very powerfull device. 
And i did forget where i put the nodeJs binaries that they stayed alive, Sorry!

But you really should consider to have the node.raumserver running on a more poewerfull device?!
Why do you want to have it running on a raumfeld device. No home-server available?

**Comment by davie2000** [comment]
Thanky for your reply!
Regarding to my 1st gen Raumfeld One the Connector² IS powerful ;-)

The only (network) device which should run 24/7 is the Connector. So I will give it a try and report back to you here.

**Comment by davie2000** [comment]
I made another symlink from "bin to lib":
`ln -s /usr/lib/nodejs/lib/node_modules /usr/lib/nodejs/bin/node_modules`
and now it seems to work!

I have successfully (?) installed node-raumserver with the following output:

> npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

>+ node-raumserver@0.1.9
added 120 packages from 147 contributors and audited 163 packages in 100.234s
found 0 vulnerabilities
