### ISSUE TITLE
Is there a way to use show a static html-page with node-raumserver?

### ISSUE THREAD

**Issue by davie2000** [ChriD/node-raumserver#86]
Hi ChriD!

Pre-Story:
I have successfully installed node-raumserver directly on my Raumfeld Connector² device and it works fast enough for me. (thanks for your 
I was now able to make some shortcuts (="Kurzbefehle") on my iPhone which call the relevant request on node-raumserver. So I can now tell Siri "Raumfeld Stop" and she will stop the music running on my Raumfeld One M (because of the request sent from my host Connector²).

Story:
I saw your "Raumserver Test-Application" (index.html from your github in the "test" directory) and copied parts to make my personal "static" html-page with some basic commands, e.g. pause is `<input type="button" id="pause" value="&#9208;" onclick="doAction('pause?id=WoZi')" />`

To request "pause" from node-raumserver, I use the following URL (which is called from static html page opened locally in my browser when I press the pause-button):
http://192.168.1.12:8080/raumserver/controller/pause?id=WoZi
This works fine, when the static page lies on my local PC and I open it locally in my browser on my pc.
But I want to open this static site from any device/browser in my local network as a (faster?) fallback for the Raumfeld-App (which is not installed on every device).

Question:
Now I am hoping that there is an (easy) way to call this (static) html-page directly from node-raumserver without making my own small node-webserver.
Something like this:
http://192.168.1.12:8080/raumserver/index.html or 
http://192.168.1.12:8080/raumserver/controller/getIndex

I hope one can come along with my "english" description.
TiA for your reply!

**Comment by ChriD** [comment]
Hi,
Well.... no... :)

You can install any static nodeJs webserver you do not have to create one by yourself. 
I think there is no need to have it inbuilt into the node-raumserver.
