### ISSUE TITLE
Installation auf Raumfeld Device

### ISSUE THREAD

**Issue by nuff04** [ChriD/node-raumserver#93]
Hi ChriD, 
ich hatte eine Anleitung zum installieren des alten Raumserver gefunden, die bei mir allerdings nicht funktioniert (der Installer findet keine Geräte). Kann der neue Raumserver auch direkt auf den Raumfeld Devices installiert werden?

Vielen Dank

**Comment by gahujipo** [comment]
Possible duplicate of https://github.com/ChriD/node-raumserver/issues/29

**Comment by ChriD** [comment]
No, sorry! There is no possibility to install the node-raumserver on raumfeld devices with the current firmware anymore. Neither it was/is not recommended to do so at all. Further more the installer itself only worked for the old c++ version of the raumserver
