### ISSUE TITLE
setVolume changes Volume on all speakers

### ISSUE THREAD

**Issue by JiroMusik** [ChriD/node-raumserver#97]
Hi,

I am using the node-raumserver on a Pi 3 for about a year now and I am very happy with it but there is one thing I got never working properly and this is the setVolume Control for adjusting the speakers without touching the others.
I use value and id parameter but even with relative=false or absolute=true it always changes every speaker.
Anyone with the same problem here?

**Comment by gahujipo** [comment]
Did you try to add ```&scope=room``` to the url? That should solve your issue. Otherwise feel free to reopen the issue.
